const map = {
  page: 'page',
  header: 'header',
  subHeader: 'sub_header',
  subSubHeader: 'sub_sub_header',
  toDo: 'to_do',
  toggle: 'toggle',
  columnList: 'column_list',
  column: 'column',
  bulletedList: 'bulleted_list',
  numberedList: 'numbered_list',
  text: 'text',
  code: 'code',
  equation: 'equation',
  divider: 'divider',
  quote: 'quote',
  callout: 'callout',
  tableOfContents: 'table_of_contents',
  breadcrumb: 'breadcrumb',
  image: 'image',
  video: 'video',
  embed: 'embed',
  codepen: 'codepen',
  audio: 'audio',
  bookmark: 'bookmark',
  collectionView: 'collection_view',
  collectionViewPage: 'collection_view_page',
  unorderedList: 'unordered_list',
  orderedList: 'ordered_list'
}

export default map